#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'apt'
cookbook 'openssl'
cookbook 'gradle', '~> 1.5.1'
cookbook 'git', '~> 4.1.0'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'maven', '~> 1.3.0'
cookbook 'docker', '~> 0.36.0'
cookbook 'zshell', '~> 0.1.1'